name: Test Suite

on:
  - pull_request

jobs:
  unit:
    name: Unit Tests & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:    
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Run lint
      run: tox -e lint
    - name: Run unit tests
      run: tox -e unit
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./.report/unit/coverage-xml
        flags: unittests # optional